### ISSUE TITLE
[D2G] Aufgaben anpassen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Deploy-to-Grading#20]
Alle Aufgaben müssen so umformuliert werden, dass sie mit der neuen Struktur zur gewollten Lösung führen.

**Comment by AKirsch1** [comment]
Da wir nur noch ein paar Demo-Aufgaben umsetzen, wird dieses Issue hier geschlossen.

@cagix Oder sollte das Issue in Homework-Solution transferiert werden?
