### ISSUE TITLE
[Tooling] Formatierung gleichziehen mit der vom PM-Dungeon

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Deploy-to-Grading#21]
Aktuell ist die Formatierung mehr oder weniger immer IntelliJ Formatierung. 
Es wäre glaube ich schlau, die Formatierung vom PM-Dungeon auch auf das Homework-Solutions anzuwenden.

**Comment by AKirsch1** [comment]
Dasselbe wie bei #20.
