### ISSUE TITLE
[D2G] Automatischen laden der Subprojekte

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Deploy-to-Grading#23]
Alle Aufgaben-Projekte sollen automatisch eingelesen werden.

In Gradle müssen die Subprojekte in `settings.gradle` hinterlegt werden. Damit wir diese Liste nicht manuell pflegen müssen, sollten diese automatisch eingelesen werden.

**Comment by AKirsch1** [comment]
Ich schließe dieses Issue hier, da es nicht der aktuellen Gradle-Umsetzung entspricht.
