### ISSUE TITLE
[D2G] Skript für die lokale Ausführung

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Deploy-to-Grading#26]
Ein Lokales Skript analog zu der GitHub-Action erstellen. 

Das bedeutet

- auschecken der Vorgaben parallel zum Repo-Dir
- Starten des Python Skripts

**Comment by AKirsch1** [comment]
Da dieses Issue für das Python-Skript ist, welches nicht mehr genutzt wird, schließe ich es hier.
