### ISSUE TITLE
[D2G] Demo für den Abschlussbericht erstellen 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Deploy-to-Grading#29]
Für den erfolgreichen Abschluss des Projekts, soll zum vorhandene Deploy-to-Abgabe System eine (präsentierbare) Demo gebastelt werden.
Das bedeutet: 
- das System für EINE konkrete Aufgabe aufsetzen
- ggf. vorhandene. Bugs fixen
  - hier muss ich mal über die offenen Issues gehen
- beispiel Abgaben für die verschiedenen Szenarien
  - fehlerfrei
  - kleine Fehler
  - abgabe nach Deadline
  - manipulierte Abgabe 

@cagix Ich würde das gerne getrennt von den ganzen anderen Repos halten. Also einen mini Kosmos für die D2A-Demo. 
Grob skizziert stelle ich mir das so vor:

**D2A-Demo-Vorgabe-Repo**
  - Aufgabentext und Vorgaben
  - D2A Skripte, Toolchain etc.

**D2A-Demo-Studi-Repo**
  - "Fork" des Dummy-Demo-Vorgabe-Repo
  - Unterschiedliche Branches für die oben genannten Szenarien (simulieren verschiedene Abgabe-Gruppen)
  - PR in den eigenen Master als Abgabe -> CI läuft

**Comment by AKirsch1** [comment]
Ich schließe das hier mal, da wir hoffentlich bis zum Ende des Projekts so weit sind, dass wir keine Demo brauchen, sondern dass das D2G vollständig funktioniert. Falls doch, können wir das Issue ja erneut öffnen.
