### ISSUE TITLE
[D2G] Einbinden der D2G-Toolchain

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Deploy-to-Grading#30]
In diesem Repository muss das D2G System eingebunden werden. 

- Dafür muss das System aber erst als [github-docker-action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) umgesetzt werden.

**Comment by AKirsch1** [comment]
Wird umgesetzt für ein Demo-Repository in #130
