### ISSUE TITLE
[D2G] Wahl der Implementierungssprache

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Deploy-to-Grading#48]
Nach dem gestrigen Meeting habe ich nochmal über die Wahl der richtigen Programmiersprache nachgedacht. Hier mal eine Zusammenfassung dazu:

| bash | Python | Java |
|--|--|--|
|- Funktioniert nicht unter Windows|- Benötigt zusätzliche Installation eines Python-Interpreters|- Muss kompiliert werden|
|- Bei größeren Skripten schnell schwer verständlich (Ich denke da ans Einlesen von YAML und Auswerten der Ergebnisse|- Wenn man es "richtig" machen will, dann wird es keinen großen Unterschied im Vergleich zur Größe des Java-Projekts geben|- Für eine solche Aufgabe könnte das Projekt unnötig groß werden|
|- Schwer zu testen (Unittests)|o Mittelding zwischen bash und Java mit dem Nachteil, dass es zusätzlich installiert werden muss. Ob das Python jetzt insgesamt besser oder schlechter macht ist schwer einzuschätzen|+ Egal wer längerfristig gesehen sonst noch daran arbeiten sollte, sollte kein Problem mit der Programmiersprache haben|
|- Keine wirkliches Dokumentationsschema|||
|+ sehr flexibel|||

Frage: Wie relevant ist eigentlich Flexibilität und wie zeichnet die sich aus? Am ehesten wird doch Flexibilität bei der Wahl der Metriken benötigt und da frage ich mich, ob bash oder Java dort einen Unterschied macht. Oder verstehe ich Flexibilität falsch?

Hier mal eine Auflistung, was meiner Einschätzung nach durch welche Sprache am einfachsten umzusetzen wäre:

| Schritt | Bezeichnung| Sprache|
| -- | -- | -- |
| 1.      | Aufgabenblatt-yml laden                                              | Python/Java |
| 2.      | Vorbereiten des Repositories                                         | bash |
| 3.      | Aufgaben-yml laden (wiederholend bis 6. für jede Aufgabe in `tasks`) | Python/Java |
| 4.      | Überschreiben der Vorlagendateien                                    | bash |
| 5.      | Ausführen des Tests (wiederholend bis 6. für jeden Test in `tests`)  | gradle |
| 6.      | Auswerten der Ergebnisse der Tests                                   | Python/Java |
| 7.      | Präsentation der Ergebnisse                                          | Python/Java, bash fürs Zippen der Ergebnisse fürs Artefakt|

Bash hat für manche Sachen definitiv Vorteile, da es einfacher ist. Sobald es aber um komplexere Datensätze geht, wäre der Einsatz von Python oder Java wahrscheinlich sinnvoller, wobei ich da eher bei Java bin.

Ich würde mal versuchen, bis nächste Woche Schritt 2 in Bash zu implementieren.

@cagix @AMatutat Was ist eure Ansicht dazu? Falls es etwas länger wird, könnt ihr auch gerne das https://github.com/Programmiermethoden/Deploy-to-Grading/labels/meeting -Label an das Issue packen.

**Comment by AMatutat** [comment]
Also, Bash halte ich auch für ungeeignet. Dafür wollen wir dann doch zu viel, und so richtig gut Bash kann irgendwie auch keiner, was später die Wartung nicht wirklich einfach macht.

Java ist halt groß....

Mein Bauchgefühl sagt mir, Python ist hier schon eine gute Wahl. Ich habe den vollen Scope nicht im Blick, aber vermutlich kann das Ganze sogar in einer Datei implementiert werden, oder? Zusätzlich gibt es für Python echt eine Tonne an Bibliotheken, die den ganzen Kleinkram (Repositories vorbereiten, Zippen usw.) für dich abnehmen. Für Java gibt es so etwas bestimmt auch, aber vermutlich ist es auch wieder typisch Java und damit klobig.

Aus deinem Vergleich geht ja auch hervor, dass die Aufgaben, die gut von Java gelöst werden können, auch von Python gut gelöst werden können. Und ich behaupte jetzt mal, mit Python kannst du deutlich angenehmer die Bash-Aufgaben übernehmen als mit Java.

Frage zur Installation: Läuft das Ding nicht eh in einem Container innerhalb der Action? Ist das dann überhaupt ein Kriterium?

Ich glaube auch nicht, dass wir bei der Wartung mit Python ein Problem bekommen. Wer Java kann, wird auch Python hinbekommen. Da sehe ich Bash deutlich kritischer

**Comment by cagix** [comment]
@AKirsch1 
So eine Action hat i.d.R. mehrere Schritte, die sie nacheinander ausführt (vgl. beispielsweise https://github.com/cagix/pandoc-lecture/blob/master/action.yml). Diese Schritte können ein oder mehrere Shell-Skript anstoßen oder Unix-Befehle direkt auf der Runner-Konsole ausführen, oder etwas in einem Docker machen oder eine andere Action triggern. In meiner Beispiel-Action mache ich aber tatsächlich nur eine Art Initialisierung der Toolchain, d.h. im aufrufenden Workflow folgt dann nach dem Aufruf der Action noch ein Make- oder Gradle-Aufruf (Beispiel: https://github.com/Programmiermethoden/PM-Lecture/blob/master/.github/workflows/slides.yaml). Aber auch das könnte direkt als `run`-Step in der Action selbst stehen.

Die Frage für mich ist, ob die Action eher monolithisch oder eher modular werden soll - soll die Action quasi nur einen Schritt machen (ein `run`) und damit wird dann ein Java- oder Python-Programm o.ä. angestoßen, was alle obigen Schritte macht, oder entsprechen die obigen Schritte tatsächlich (mehr oder weniger) den Steps in der Action?  

Die zweite Frage ist, ob man das flexibel halten kann. In der GH-Action selbst würde ich versuchen, alles direkt im Runner auszuführen. Wenn man dabei darauf achtet, dass man beispielsweise Shell-Skripte oder Gradle oder was auch immer anstößt, dann kriegt man das auch relativ elegant parallel in eine Docker-Definition rein und kann das dann prima lokal ausführen.

Wenn ich mir oben definierten Schritte anschaue, sind manche Dinge (wie (2), (4), (5)) schon deutlich einfacher als Shellskript umzusetzen: Da stehen dann einfach ein paar Git-Befehle oder Gradle-Aufrufe drin. Ich glaube, da brichst Du Dir mit Java (und auch Python) ziemlich was ab ... (aber es sollte natürlich auch gehen). Ich bin aber bei Dir, dass die Auswertung der Konfiguration und der Log-Files (Ergebnisse der einzelnen Metriken) nicht sinnvoll in der Shell geht. Bei der Konfiguration (Schritt 1) könnte ich mir vorstellen, dass das beispielsweise über ein kleines Programm erledigt wird, welches ein paar Umgebungsvariablen für den nächsten Schritt setzt oder das auszuführende Gradle-Skript einliest und Werte überschreibt und wieder ausgibt. Die Auswertung der einzelnen Metriken könnte dann auch wieder in einzelnen Programmen erledigt werden (je eins pro Tool). @AMatutat war grad schneller mit dem Tippen - aber ich bin auch nicht sicher, ob für diese Zwecke Java wirklich einfacher ist. Die Installation auf dem Runner ist per Step und vordefinierter Action schnell erledigt (da gibts für Java und auch Python bereits Actions direkt von GitHub), und im Docker ist das auch mit einem "apt install" getan.

**Comment by cagix** [comment]
Hmmm, wir haben grad zwei Erzählstränge: @AMatutat macht sich stark für eine Python-Lösung, während ich die Diskussion Monolith vs. Modulares System aufgemacht habe. 

Prinzipiell wäre ich eher für eine modulare Lösung, wenn sie sich denn sinnvoll darstellen lässt. Dann kann man in der Action Schritte an- und ausknipsen (beispielsweise über Eingangsvariablen beim Aufruf der Action). Wenn das jetzt aber nicht lösbar erscheint, dann muss eine monolithische Lösung vielleicht erstmal reichen. 

Die Sprache ist mir relativ egal. Ich würde nur gern schauen, dass man nach Möglichkeit Dinge wie Makefiles und/oder Gradle nutzt zur Steuerung der Sachen. Ob dann damit ein Shellskript oder ein Python-Skript oder ein Java-Programm oder ein Haskell-Moped angestoßen wird, ist mir eigentlich relativ egal :)

**Comment by AKirsch1** [comment]
Ich antworte hier mal auf die Kommentare von euch beiden gleichzeitig:

Vorweg: Java scheint mir nach euren Kommentaren raus zu sein.
Ansonsten: In PR #51 habe ich ein Beispiel-Bashskript hochgeladen. Wenn man die Aufgaben klein genug stückelt pro Skript, dann sollten sich einige Sachen wirklich gut umsetzen lassen.

Und wenn wir von Java weg sind, dann tendiere ich auch eher zum modularen System (Dann könnte ich auch von Anfang an kleine PRs machen :D). Ganz oben hatte ich ja schon geschrieben, was man womit machen könnte. Alles, was zu komplex ist, würde ich dann als kleine Python-Skripte umsetzen. Insbesondere wenn @AMatutat sagt, dass Python kein Problem ist. Und wenn die Bash-Skripte simpel genug bleiben, dann sollte das auch kein Problem sein.

Nur dass wir von Schritt 3 bis 6 zwei Schleifen brauchen, finde ich bei einem modularen System nicht so schön. [Hier](https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/) habe ich zwar gefunden, wie man das in GH Actions lösen kann. Schnell verständlich für einen, der das zum ersten Mal sieht, finde ich es aber nicht.

**Comment by cagix** [comment]
> Java scheint mir nach euren Kommentaren raus zu sein.

Würde ich so strikt nicht formulieren :)  Im Moment drehen wir mögliche Konzepte hin und her und versuchen, mögliche Vor- und Nachteile abzuklopfen. 

> Nur dass wir von Schritt 3 bis 6 zwei Schleifen brauchen

Schleifen sind tatsächlich ein Punkt, wo es bei der Realisierung direkt in der Action eher hässlich wird - zumal man das ja dann auch nochmal geeignet für den Docker realisieren muss. 

Aber: Sind es denn tatsächlich "Schleifen" oder sind es nicht vielmehr Aufrufe eines Skripts o.ä. jeweils für verschiedene Tasks? Hier kommt mir sowas wie Makefiles in den Sinn: Man kann dort Variablen dynamisch setzen, indem man andere Skripte o.ä. ausführt und den Rückgabewert in einer Variable speichert. Und dann kann man basierend darauf ein Target haben, was quasi die Schleife realisiert. Von außen in der Action würde man dann nur `make target` ausführen ...

**Comment by AMatutat** [comment]
Modular klingt meist besser, aber wenn ich das so lese, dann zerlegen wir uns das an ganz viele unterschiedliche Stellen, oder?
Also nur mal was ich (zu glaube) verstanden habe
- Wir haben Aktionen in der Action
    - Frage: Wenn wir "logik" in der Action implementieren, wird ein lokales ausführen nur schwerer, oder? Weiß nicht wie aktuell der Gedanke noch ist, dass auch lokla ausführen zu können. 
    -  Irgendwelche Skripte (ob Python, bash oder beides) die innerhalb der Action nochmal aufgerufen werden
    - Build-Skripte
    - potenzielle Konfigurationsdateien

Irgendwie scheint mir das viel Zeugs an vielen unterschiedlichen Baustellen zu sein.

**Comment by cagix** [comment]
deshalb ja auch mein vorschlag mit passenden skripten/programmen, die einzelne teilaufgaben erledigen können und das dann über buildskripte zu einem größeren ganzen zusammenbauen. und in der aktion kann man dann gezielt einzelne sachen anstoßen: (1) ist vermutlich die initialisierung von variablen (über ein skript/programm), (2) ist ein eigenständiges target, (3)-(6) sind je einzelne schritte im buildskript, die über die in (1) initialisierte variablen laufen. und (7) ist dann nochmal ein eigener schritt.

**Comment by AKirsch1** [comment]
> Sind es denn tatsächlich "Schleifen" oder sind es nicht vielmehr Aufrufe eines Skripts o.ä. jeweils für verschiedene Tasks?

Wir haben ja zwei unterschiedliche "Schleifen". Zum einen die Iteration über die einzelnen Aufgaben: Da passiert auf jeden Fall immer das Gleiche in einem anderen Unterordner. Darin haben wir dann aber die Liste mit den Metriken, wo bei jeder Metrik etwas anderes ausgeführt wird. Ich bin mir nur nicht sicher, ob wir dafür mit Make noch ein Tool brauchen. Ist es da nicht einfacher, sich die "Schleife" selbst in einem Skript zu programmieren? Dann müsste man, wie ich finde, aber auch die komplette Logik aus der Action in ein Skript auslagern, sonst haben wir die an zwei verschiedenen Stellen (Wäre beim Makefile ja auch der Fall, oder?).

> Wenn wir "logik" in der Action implementieren, wird ein lokales ausführen nur schwerer, oder? Weiß nicht wie aktuell der Gedanke noch ist, dass auch lokla ausführen zu können.

Lokal ausführbar soll das immer noch sein. Dann bräuchte man wahrscheinlich ein bash/Python-Skript, welches das Gleiche macht, falls wir Logik in der Action implementieren. Wenn man, wie oben geschrieben, die Logik auslagern würde, dann hätten wir diese Unterscheidung aber nicht mehr.

Ich habe an dieses Issue mal das Meeting Label gepappt.

**Comment by AKirsch1** [comment]
Notizen aus Meeting am 28.06.:
- Skript, welches andere Sachen anstößt
- Sprache relativ egal
- Sachen möglichst modular/flexibel
- Wenn bash, dann make
- Python ist auf einem Runner schon vorinstalliert
