### ISSUE TITLE
[D2G] Sammlung an Konferenzen für D2G

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Deploy-to-Grading#6]
## Konkretes:

**[Workshop "Automatische Bewertung von Programmieraufgaben"](https://www.abp-workshop.de/)** (Deutschland) (h-Index: Nichts gefunden)

Einreichfrist: 15. Juni 2023 12:00 Uhr
Workshop: 12.-13. Oktober 2023

## Weiteres:

**[ACM/SIGCSE conference on Innovation and Technology in Computer Science Education (ITiCSE)](https://iticse.acm.org/2023/)** (Europa) (h-Index: 32)
**[SIGCSE Technical Symposium](https://sigcse.org/events/symposia/index.html)** (USA) (h-Index: 24 (Irgendwie kann ich mir nicht vorstellen, dass der Europäische besser sein soll. Dieses Symposium ist laut SIGCSE größer.)

Bereits zu spät für beides, aber unter SIGCSE habe ich schon ein paar Paper zum Thema AutoGrader gesehen. Für ITiCSE 2024 könnte die nächste Deadline im Januar 2024 sein, habe aber noch nicht genaueres gefunden.

**[IEEE Transactions on Learning Technologies](https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4620076)** (h-Index: 52)

Als Alternative noch ein Journal.

**Comment by cagix** [comment]
@AKirsch1 Kannst Du das (Infos oben aus dem Kommentar und dem Wiki) bitte noch mit der Liste in https://github.com/Programmiermethoden/Dungeon/blob/master/doc/related_work/conferences.md abgleichen und fehlende Beiträge und Inhalte dort ergänzen?

Ich finde auch die Zeiten (Deadline Einreichung, Termin Tagung) hilfreich - dann kann man später schnell sehen, wann man ggf. aktiv werden sollte. Bitte die entsprechenden Spalten in https://github.com/Programmiermethoden/Dungeon/blob/master/doc/related_work/conferences.md  noch ergänzen. 

Ich mache dazu das Ticket nochmal auf.

**Comment by AKirsch1** [comment]
Kann ich machen. Ist es eigentlich sinnvoll, sowohl im doc-Ordner als auch im Wiki eine Liste zu führen? Die sind ja jetzt schon inkonsistent.

**Comment by cagix** [comment]
> Kann ich machen. Ist es eigentlich sinnvoll, sowohl im doc-Ordner als auch im Wiki eine Liste zu führen? Die sind ja jetzt schon inkonsistent.

wiki (-eintrag) kommt danach weg, die issues werden geschlossen. die doku in docs/ ist dann die ssot (single source of truth).
