### ISSUE TITLE
CODEOWNERS: Einstellungen passen nicht

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Deploy-to-Grading#65]
Siehe https://github.com/Programmiermethoden/Deploy-to-Grading/pull/59#issuecomment-1644106613: 

Ich habe ein Approval abgegeben, der PR steht aber noch auf "rot", weil das Dungeon-Team Codeowner ist und ein Review abgeben müsste und ich da (absichtlich) nicht im Team drin bin.

Lösungsansätze:
(a) Ich könnte mich wieder in das Dungeon-Team eintragen. Das will ich aber eigentlich nicht, weil ich dann eben auch wieder immer den ganzen "Kleinkram" in die Timeline kriege.
(b) Ich könnte mich in der CODEOWNERS noch explizit direkt dazu schreiben. Aber ich glaube, das ist im Endeffekt das gleiche wie (a), nur begrenzt auf die PR in diesem Repo.
(c) Wir lassen es bei dem Default-Eintrag. Damit kriege ich hier automatisch bei PR's ein Review, was für Dich einfacher ist. Wenn Du die PR als Draft-PR erstellst, poppt das dann nicht bei mir auf, so lange die PR den Draft-Status haben.
(d) Wir werfen die CODEOWNERS komplett raus. Dann müsstest Du mich manuell zum Review assignen, wenn Du jeweils soweit bist. 

Aus meiner Sicht könnten (b) oder (c) eine Lösung darstellen, wobei (b) vielleicht sogar flexibler ist: Das Dungeon-Team oder ich muss ein Review abgeben ... 

@AKirsch1 Was denkst Du?

**Comment by AKirsch1** [comment]
> @AKirsch1 Was denkst Du?

Könnte es bei Version (c) im Hinblick auf den August irgendwelche Probleme geben? Dann wäre Option (b) wahrscheinlich besser, oder?
