### ISSUE TITLE
[D2G] Metrik JGrade

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Deploy-to-Grading#71]
Zusätzlich zur JUnit Metrik soll eine JGrade Metrik eingebunden werden, um individuelle Punkte für Tests vergeben zu können.

**Comment by AKirsch1** [comment]
Im heutigen WiMi-Meeting haben wir uns dazu entschieden, JGrade vorerst nicht einzusetzen. Das hat folgende Gründe:

- JGrade wird nicht aktiv maintained. Das offizielle Repository hat seit Ende 2020 keine Updates mehr bekommen und es steht auch dort im README, dass der Autor nicht mehr aktiv daran arbeitet. Es existiert zwar ein Fork, in dem vor 6 Monaten das letzte Mal aktiv gearbeitet wurde, aber auch hier ist unklar, ob weiterhin aktiv daran gearbeitet wird.
- Auch die Umsetzung des Ausführens ist nicht schön gelöst, da das Kompilieren der Tests über ein Bash-Skript passiert. Gleiches beim Ausführen. Eine Integration in Gradle und Maven gibt es nicht.

**Comment by AKirsch1** [comment]
@cagix Kannst du hierzu eine kurze Rückmeldung geben? Wenn ein Ok von deiner Seite kommt, dann kann das hier geschlossen werden.

Die Funktionalität, die wir hiermit erreichen wollten, ist bereits über die JUnit-Metrik erfüllt.

**Comment by cagix** [comment]
> Die Funktionalität, die wir hiermit erreichen wollten, ist bereits über die JUnit-Metrik erfüllt.

Naja, wenn das so ist, brauchen wir JGrade ja nicht? Zumal, wenn das Ding nicht mehr maintained ist ...

**Comment by AKirsch1** [comment]
> brauchen wir JGrade ja nicht?

Ja genau, dann hätten wir auch eine Abhängigkeit weniger.

**Comment by cagix** [comment]
true that, wobei ein aspekt ja auch war zu zeigen, wie offen das framework für externe tools ist. das würde dann wegfallen.

anyway. wenn die ursprünglichen ziele mit deinem vorschlag erreicht werden, dann los.

**Comment by AKirsch1** [comment]
Dann schließe ich das Issue hiermit als Not planned, da die Funktionalität bereits durch die JUnit-Metrik umgesetzt ist.
