### ISSUE TITLE
[D2G] Ergebnisse der Toolchain extrahieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Deploy-to-Grading#8]
Die Ergebnisse der Toolchain werden in verschiedenen Dateien gespeichert.
Diese müssen im Python Skript eingelesen und ausgewertet werden. 
Dafür soll für jeden Task für jedes Kriterium eine "Map" angelegt werden.

- [ ] JUnit
    - Wie viele Tests gibt es im LoesungsTestSuit?
    - Wie viele sind gescheitert?
- [ ] Spotbugs
    - Wie viele Probleme gibt es pro Stufe?  
- [ ] Checkstyle
    - Wie viele Probleme gibt es pro Stufe? 
- [ ] (Spotless)
    - nach absprache mit @AHeinisch

**Comment by AKirsch1** [comment]
Ich schließe das Issue hier, da die Ergebnisse im Grunde mit #62 und den `*_eval.py`-Skripten in den jeweiligen Metrik-PRs ausgewertet werden. Das Berechnen der Gesamtpunktzahl für das Assignment und die einzelnen Aufgaben sehe ich eher in #16 und #17.
